pipeline {
    agent any

    tools {
        maven 'Maven'    
        jdk 'JDK11'      
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mahii47/OrangeHRMProject.git'
            }
        }

        stage('Build') {
            steps {
                dir('OrangeHRMWebsite') {  
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('OrangeHRMWebsite') {
                    
                    sh 'mvn test'
                }
            }
        }
    }

    post {
        always {
            
            archiveArtifacts artifacts: 'OrangeHRMWebsite/target/screenshots/*.png', allowEmptyArchive: true
            junit 'OrangeHRMWebsite/target/surefire-reports/*.xml'
        }
        failure {
            echo "Build Failed! Check screenshots/logs in Jenkins."
        }
        success {
            echo " Build Passed!"
        }
    }
}
